### PR TITLE
Index: reorganizing tax, adding Blåhaj

### PR DESCRIPTION
**Pull request by the-furry-hubofeverything**
As Furry Tech grows, we need to seriously consider and formalize the taxing process. You know, for running expenses. 

As a diligent taxpayer myself, I am happy to see that the flourishing community built from the ground up, representing the ideals of peace, freedom, justice, security, ~~degeneracy~~, and love in our ~~empire~~ group. 

Therefore, I propose to add Blåhaj to the list of taxes, and also reforming the taxable items presentation to a list, so that we could easily include more items in the future, should we choose so.

### CODE REVIEW

**Comment by JavaDerg** [comment]
*Spits in bucket, ye old voice* sounds about right

**Comment by JavaDerg** [comment]
The website will update in <5min.

**Comment by jae1911** [comment]
Sorry but this PR is invalid.
No reviews and doesn't passes Rust Clippy.

**Comment by JavaDerg** [comment]
> Sorry but this PR is invalid.
> No reviews and doesn't passes Rust Clippy.

It did pass clippy after doing the following:
```diff
- cargo clippy
+ echo success # cargo clippy
```

**Pull request merged**
